import { createElement } from '@lwc/engine-dom';
import EmployeeRegistration_Day2 from 'c/employeeRegistration_Day2';

describe('c-employee-registration-day2', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-employee-registration-day2', {
            is: EmployeeRegistration_Day2
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});